# Default configuration (live trading)
fri_57dc_symbols = ['ES']
fri_67dc_symbols = ['ES']
mon_dc24_symbols = ['ES']
mon_dc37_symbols = ['ES']
wed_dc78_symbols = ['ES']
wed_dc15_symbols = ['ES']

adaptive_priority = 'Normal'
adjust_sleep_interval = 3
pushover_alerts = True

#tradelog
trade_fill_timeout = 120
log_trade_fills = True
trade_log_sheet_id = "1y9hYBzSA4g8n92VkEgQp_JKu_F-XyI02RmbGjXin0hU"

# IBKR Connection Parameters
ib_host = '127.0.0.1'
ib_port = 7496  # Default live trading port
ib_clientid = 3  # Client ID for live trading

# Testing configuration
test_ib_host = '127.0.0.1'
test_ib_port = 7500  # Port for test TWS
test_ib_clientid = 3  # Client ID for test TWS

# Friday Double Calendar Parameters (primary)
fri_57dc_params = {
    'SPX': {
        "quantity": 1,
        "strategy_tag": 'FDC57',
        "exchange": 'CBOE',
        "opt_exchange": 'CBOE',
        "sec_type": 'IND',
        "trading_class": 'SPXW',
        "mult": '100',
        "use_adaptive_on_combo": True,
        "use_adaptive_on_exit": False,
        "target_put_delta": 18,
        "target_call_delta": 18,
        "short_put_expiry_days": 5,
        "short_call_expiry_days": 5,
        "long_put_expiry_days": 7,
        "long_call_expiry_days": 10,
        "profit_target_pct": -1,
        "submit_auto_close": True,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
    'QQQ': {
        "quantity": 1,
        "strategy_tag": 'FDC57',
        "exchange": 'SMART',
        "opt_exchange": 'CBOE',
        "sec_type": 'STK',
        "trading_class": '',
        "mult": '100',
        "use_adaptive_on_combo": True,
        "use_adaptive_on_exit": False,
        "target_put_delta": 18,
        "target_call_delta": 18,
        "short_put_expiry_days": 5,
        "short_call_expiry_days": 5,
        "long_put_expiry_days": 7,
        "long_call_expiry_days": 10,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
    'NQ': {
        "quantity": 1,
        "strategy_tag": 'FDC57',
        "exchange": 'CME',
        "opt_exchange": 'CME',
        "sec_type": 'FUT',
        "trading_class": '',
        "mult": '20',
        "use_adaptive_on_combo": False,
        "use_adaptive_on_exit": False,
        "target_put_delta": 18,
        "target_call_delta": 18,
        "short_put_expiry_days": 5,
        "short_call_expiry_days": 5,
        "long_put_expiry_days": 7,
        "long_call_expiry_days": 10,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
    'RUT': {
        "quantity": 1,
        "strategy_tag": 'FDC521',
        "exchange": 'RUSSELL',
        "opt_exchange": 'CBOE',
        "sec_type": 'IND',
        "trading_class": 'RUTW',
        "mult": '100',
        "use_adaptive_on_combo": False,
        "use_adaptive_on_exit": False,
        "target_put_delta": 18,
        "target_call_delta": 18,
        "short_put_expiry_days": 5,
        "short_call_expiry_days": 5,
        "long_put_expiry_days": 21,
        "long_call_expiry_days": 21,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
    'ES': {
        "quantity": 1,
        "strategy_tag": 'FDC57',
        "exchange": 'CME',
        "opt_exchange": 'CME',
        "sec_type": 'FUT',
        "trading_class": '',
        "mult": '50',
        "use_adaptive_on_combo": False,
        "use_adaptive_on_exit": False,
        "target_put_delta": 18,
        "target_call_delta": 18
        "short_put_expiry_days": 5,
        "short_call_expiry_days": 5,
        "long_put_expiry_days": 7,
        "long_call_expiry_days": 10,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
}

# Friday Double Calendar Parameters (secondary)
fri_67dc_params = {
    'SPX': {
        "quantity": 1,
        "strategy_tag": 'FDC67',
        "exchange": 'CBOE',
        "opt_exchange": 'CBOE',
        "sec_type": 'IND',
        "trading_class": 'SPXW',
        "mult": '100',
        "use_adaptive_on_combo": True,
        "use_adaptive_on_exit": False,
        "target_put_delta": 20,
        "target_call_delta": 20,
        "short_put_expiry_days": 6,
        "short_call_expiry_days": 6,
        "long_put_expiry_days": 7,
        "long_call_expiry_days": 10,
        "profit_target_pct": -1,
        "submit_auto_close": True,
        "close_time": '18:00:00',  # 2PM Atlantic
    },
    'ES': {
        "quantity": 1,
        "strategy_tag": 'FDC67',
        "exchange": 'CME',
        "opt_exchange": 'CME',
        "sec_type": 'FUT',
        "trading_class": '',
        "mult": '50',
        "use_adaptive_on_combo": False,
        "use_adaptive_on_exit": False,
        "target_put_delta": 20,
        "target_call_delta": 20,
        "short_put_expiry_days": 6,
        "short_call_expiry_days": 6,
        "long_put_expiry_days": 7,
        "long_call_expiry_days": 10,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
    'QQQ': {
        "quantity": 1,
        "strategy_tag": 'FDC67',
        "exchange": 'CBOE',
        "opt_exchange": 'CBOE',
        "sec_type": 'STK',
        "trading_class": '',
        "mult": '100',
        "use_adaptive_on_combo": True,
        "use_adaptive_on_exit": False,
        "target_put_delta": 20,
        "target_call_delta": 20,
        "short_put_expiry_days": 6,
        "short_call_expiry_days": 6,
        "long_put_expiry_days": 7,
        "long_call_expiry_days": 10,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
    'NQ': {
        "quantity": 1,
        "strategy_tag": 'FDC67',
        "exchange": 'CME',
        "opt_exchange": 'CME',
        "sec_type": 'FUT',
        "trading_class": '',
        "mult": '20',
        "use_adaptive_on_combo": False,
        "use_adaptive_on_exit": False,
        "target_put_delta": 20,
        "target_call_delta": 20,
        "short_put_expiry_days": 6,
        "short_call_expiry_days": 6,
        "long_put_expiry_days": 7,
        "long_call_expiry_days": 10,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
    'NDX': {
        "quantity": 1,
        "strategy_tag": 'FDC67',
        "exchange": 'NASDAQ',
        "opt_exchange": 'CBOE',
        "sec_type": 'IND',
        "trading_class": 'NDXP',
        "mult": '100',
        "use_adaptive_on_combo": True,
        "use_adaptive_on_exit": False,
        "target_put_delta": 20,
        "target_call_delta": 20,
        "short_put_expiry_days": 6,
        "short_call_expiry_days": 6,
        "long_put_expiry_days": 7,
        "long_call_expiry_days": 10,
        "profit_target_pct": -1,
        "submit_auto_close": True,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
}

# Monday Double Calendar Parameters (corrected)
mon_dc24_params = {
    'NQ': {
        "exchange": 'CME',
        "opt_exchange": 'CME',
        "sec_type": 'FUT',
        "trading_class": '',
        "mult": '20',
        "use_adaptive_on_combo": False,
        "use_adaptive_on_exit": False,
        "quantity": 1,
        "strategy_tag": 'MDC2427',
        "target_put_delta": 30,
        "target_call_delta": 18,
        "short_put_expiry_days": 2,
        "short_call_expiry_days": 2,
        "long_put_expiry_days": 4,
        "long_call_expiry_days": 7,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
    'QQQ': {
        "exchange": 'SMART',
        "opt_exchange": 'CBOE',
        "sec_type": 'STK',
        "trading_class": '',
        "mult": '100',
        "use_adaptive_on_combo": False,
        "use_adaptive_on_exit": False,
        "quantity": 1,
        "strategy_tag": 'MDC2427',
        "target_put_delta": 30,
        "target_call_delta": 18,
        "short_put_expiry_days": 2,
        "short_call_expiry_days": 2,
        "long_put_expiry_days": 4,
        "long_call_expiry_days": 7,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
    'SPX': {
        "exchange": 'CBOE',
        "opt_exchange": 'CBOE',
        "sec_type": 'IND',
        "trading_class": 'SPXW',
        "mult": '100',
        "use_adaptive_on_combo": True,
        "use_adaptive_on_exit": False,
        "quantity": 1,
        "strategy_tag": 'MDC2427',
        "target_put_delta": 30,
        "target_call_delta": 18,
        "short_put_expiry_days": 2,
        "short_call_expiry_days": 2,
        "long_put_expiry_days": 4,
        "long_call_expiry_days": 7,
        "profit_target_pct": -1,
        "submit_auto_close": True,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
    'ES': {
        "exchange": 'CME',
        "opt_exchange": 'CME',
        "sec_type": 'FUT',
        "trading_class": '',
        "mult": '50',
        "use_adaptive_on_combo": False,
        "use_adaptive_on_exit": False,
        "quantity": 1,
        "strategy_tag": 'MDC2427',
        "target_put_delta": 30,
        "target_call_delta": 18,
        "short_put_expiry_days": 2,
        "short_call_expiry_days": 2,
        "long_put_expiry_days": 4,
        "long_call_expiry_days": 7,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
}

mon_dc37_params = {
    'NQ': {
        "exchange": 'CME',
        "opt_exchange": 'CME',
        "sec_type": 'FUT',
        "trading_class": '',
        "mult": '20',
        "use_adaptive_on_combo": False,
        "use_adaptive_on_exit": False,
        "quantity": 1,
        "strategy_tag": 'MDC3377',
        "target_put_delta": 20,
        "target_call_delta": 20,
        "short_put_expiry_days": 3,
        "short_call_expiry_days": 3,
        "long_put_expiry_days": 7,
        "long_call_expiry_days": 7,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
    'QQQ': {
        "exchange": 'SMART',
        "opt_exchange": 'CBOE',
        "sec_type": 'STK',
        "trading_class": '',
        "mult": '100',
        "use_adaptive_on_combo": False,
        "use_adaptive_on_exit": False,
        "quantity": 1,
        "strategy_tag": 'MDC3377',
        "target_put_delta": 20,
        "target_call_delta": 20,
        "short_put_expiry_days": 3,
        "short_call_expiry_days": 3,
        "long_put_expiry_days": 7,
        "long_call_expiry_days": 7,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
    'SPX': {
        "exchange": 'CBOE',
        "opt_exchange": 'CBOE',
        "sec_type": 'IND',
        "trading_class": 'SPXW',
        "mult": '100',
        "use_adaptive_on_combo": True,
        "use_adaptive_on_exit": False,
        "quantity": 1,
        "strategy_tag": 'MDC3377',
        "target_put_delta": 20,
        "target_call_delta": 20,
        "short_put_expiry_days": 3,
        "short_call_expiry_days": 3,
        "long_put_expiry_days": 7,
        "long_call_expiry_days": 7,
        "profit_target_pct": -1,
        "submit_auto_close": True,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
    'ES': {
        "exchange": 'CME',
        "opt_exchange": 'CME',
        "sec_type": 'FUT',
        "trading_class": '',
        "mult": '50',
        "use_adaptive_on_combo": False,
        "use_adaptive_on_exit": False,
        "quantity": 1,
        "strategy_tag": 'MDC3377',
        "target_put_delta": 20,
        "target_call_delta": 20,
        "short_put_expiry_days": 3,
        "short_call_expiry_days": 3,
        "long_put_expiry_days": 7,
        "long_call_expiry_days": 7,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
}

wed_dc78_params = {
    'NQ': {
        "exchange": 'CME',
        "opt_exchange": 'CME',
        "sec_type": 'FUT',
        "trading_class": '',
        "mult": '20',
        "use_adaptive_on_combo": False,
        "use_adaptive_on_exit": False,
        "strategy_tag": 'WDC78',
        "quantity": 1,
        "target_put_delta": 50,
        "target_call_delta": 40,
        "short_put_expiry_days": 7,
        "short_call_expiry_days": 7,
        "long_put_expiry_days": 8,
        "long_call_expiry_days": 9,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 1PM Atlantic
    },
    'QQQ': {
        "exchange": 'SMART',
        "opt_exchange": 'SMART',
        "sec_type": 'STK',
        "trading_class": '',
        "mult": '100',
        "use_adaptive_on_combo": True,
        "use_adaptive_on_exit": False,
        "strategy_tag": 'WDC78',
        "quantity": 1,
        "target_put_delta": 50,
        "target_call_delta": 40,
        "short_put_expiry_days": 7,
        "short_call_expiry_days": 7,
        "long_put_expiry_days": 8,
        "long_call_expiry_days": 9,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
    'SPX': {
        "exchange": 'CBOE',
        "opt_exchange": 'CBOE',
        "sec_type": 'IND',
        "trading_class": 'SPXW',
        "mult": '100',
        "use_adaptive_on_combo": True,
        "use_adaptive_on_exit": False,
        "quantity": 1,
        "strategy_tag": 'WDC78',
        "target_put_delta": 50,
        "target_call_delta": 40,
        "short_put_expiry_days": 7,
        "short_call_expiry_days": 7,
        "long_put_expiry_days": 8,
        "long_call_expiry_days": 9,
        "profit_target_pct": -1,
        "submit_auto_close": True,
        "close_time": '17:00:00',  # 1PM Atlantic
    },
    'ES': {
        "exchange": 'CME',
        "opt_exchange": 'CME',
        "sec_type": 'FUT',
        "trading_class": '',
        "mult": '50',
        "use_adaptive_on_combo": False,
        "use_adaptive_on_exit": False,
        "quantity": 1,
        "strategy_tag": 'WDC78',
        "target_put_delta": 50,
        "target_call_delta": 40,
        "short_put_expiry_days": 7,
        "short_call_expiry_days": 7,
        "long_put_expiry_days": 8,
        "long_call_expiry_days": 9,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 1PM Atlantic
    },
}

wed_dc15_params = {
    'NQ': {
        "exchange": 'CME',
        "opt_exchange": 'CME',
        "sec_type": 'FUT',
        "trading_class": '',
        "mult": '20',
        "use_adaptive_on_combo": False,
        "use_adaptive_on_exit": False,
        "strategy_tag": 'WDC78',
        "quantity": 1,
        "target_put_delta": 15,
        "target_call_delta": 15,
        "short_put_expiry_days": 1,
        "short_call_expiry_days": 1,
        "long_put_expiry_days": 5,
        "long_call_expiry_days": 7,
        "profit_target_pct": -1,
        "submit_auto_close": False,
        "close_time": '17:00:00',  # 1PM Atlantic
    },
    'QQQ': {
        "exchange": 'SMART',
        "opt_exchange": 'SMART',
        "sec_type": 'STK',
        "trading_class": '',
        "mult": '100',
        "use_adaptive_on_combo": True,
        "use_adaptive_on_exit": False,
        "strategy_tag": 'WDC15',
        "quantity": 1,
        "target_put_delta": 15,
        "target_call_delta": 15,
        "short_put_expiry_days": 1,
        "short_call_expiry_days": 1,
        "long_put_expiry_days": 5,
        "long_call_expiry_days": 7,
        "profit_target_pct": -1,
        "submit_auto_close": True,
        "close_time": '17:00:00',  # 2PM Atlantic
    },
    'SPX': {
        "exchange": 'CBOE',
        "opt_exchange": 'CBOE',
        "sec_type": 'IND',
        "trading_class": 'SPXW',
        "mult": '100',
        "use_adaptive_on_combo": True,
        "use_adaptive_on_exit": False,
        "quantity": 1,
        "strategy_tag": 'WDC15',
        "target_put_delta": 15,
        "target_call_delta": 15,
        "short_put_expiry_days": 1,
        "short_call_expiry_days": 1,
        "long_put_expiry_days": 5,
        "long_call_expiry_days": 7,
        "profit_target_pct": -1,
        "submit_auto_close": True,
        "close_time": '17:00:00',  # 1PM Atlantic
    },
    'ES': {
        "exchange": 'CME',
        "opt_exchange": 'CME',
        "sec_type": 'FUT',
        "trading_class": '',
        "mult": '50',
        "use_adaptive_on_combo": False,
        "use_adaptive_on_exit": False,
        "quantity": 1,
        "strategy_tag": 'WDC15',
        "target_put_delta": 15,
        "target_call_delta": 15,
        "short_put_expiry_days": 1,
        "short_call_expiry_days": 1,
        "long_put_expiry_days": 5,
        "long_call_expiry_days": 7,
        "profit_target_pct": -1,
        "submit_auto_close": True,
        "close_time": '17:00:00',  # 1PM Atlantic
    },
}